### ISSUE TITLE
Can you provide papers

### ISSUE THREAD

**Issue by laugh12321** [BluesLmy/FNNC_unmixing#1]
&emsp;您好，我對您的研究很感興趣。但在 IGRASS 2020 沒有找到這篇論文（是[這篇](https://doi.org/10.1016/j.sigpro.2020.107672)嗎），能否提供份電子版論文。🙏🙏🙏🙏🙏

**Comment by Aliceoil** [comment]
您好，请问您找到这篇文章了吗？如果找到了，可以分享一下吗？感谢感谢
